In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
random.seed(42)
np.random.seed(42)

In [3]:
import pandas as pd
import numpy as np
import random

random.seed(42)
np.random.seed(42)

data = []

# Running - 2000
for i in range(2000):
    data.append([
        f"LOOM{i+1:04d}",
        round(random.uniform(32,38),2),
        round(random.uniform(0.5,2.0),2),
        random.randint(1180,1220),
        round(random.uniform(58,62),2),
        round(random.uniform(4.2,5.2),2),
        random.randint(50,500),
        "Running"
    ])

# Maintenance - 1500
for i in range(2000,3500):
    data.append([
        f"LOOM{i+1:04d}",
        round(random.uniform(39,44),2),
        round(random.uniform(2.0,5.0),2),
        random.randint(1150,1185),
        round(random.uniform(55,58),2),
        round(random.uniform(5.2,6.0),2),
        random.randint(500,1200),
        "Maintenance"
    ])

# Critical - 1000
for i in range(3500,4500):
    data.append([
        f"LOOM{i+1:04d}",
        round(random.uniform(45,50),2),
        round(random.uniform(5.0,8.0),2),
        random.randint(1080,1145),
        round(random.uniform(50,55),2),
        round(random.uniform(6.0,7.0),2),
        random.randint(1200,2500),
        "Critical"
    ])

# Stopped - 500
for i in range(4500,5000):
    data.append([
        f"LOOM{i+1:04d}",
        round(random.uniform(28,35),2),
        0,
        0,
        round(random.uniform(50,60),2),
        0,
        random.randint(0,2500),
        "Stopped"
    ])

df = pd.DataFrame(data, columns=[
    "Machine_ID",
    "Temperature",
    "Vibration",
    "RPM",
    "Humidity",
    "Power",
    "Running_Hours",
    "Status"
])

df.head()

,Machine_ID,Temperature,Vibration,RPM,Humidity,Power,Running_Hours,Status
0,LOOM0001,35.84,0.54,1197,58.98,4.34,102,Running
1,LOOM0002,36.06,1.84,1185,60.36,4.23,97,Running
2,LOOM0003,33.31,1.26,1181,60.24,4.92,409,Running
3,LOOM0004,35.27,0.83,1217,59.11,5.07,438,Running
4,LOOM0005,36.83,1.55,1201,59.11,4.42,440,Running

In [4]:
df.shape

(5000, 8)

In [5]:
df["Status"].value_counts()

Status
Running        2000
Maintenance    1500
Critical       1000
Stopped         500
Name: count, dtype: int64

In [6]:
from google.colab import files

files.download("textwin_sensor_dataset.csv")

FileNotFoundError: Cannot find file: textwin_sensor_dataset.csv

In [7]:
df.head()

,Machine_ID,Temperature,Vibration,RPM,Humidity,Power,Running_Hours,Status
0,LOOM0001,35.84,0.54,1197,58.98,4.34,102,Running
1,LOOM0002,36.06,1.84,1185,60.36,4.23,97,Running
2,LOOM0003,33.31,1.26,1181,60.24,4.92,409,Running
3,LOOM0004,35.27,0.83,1217,59.11,5.07,438,Running
4,LOOM0005,36.83,1.55,1201,59.11,4.42,440,Running

df.shape

In [10]:
df.shape

(5000, 8)

In [9]:
import os

os.listdir()

['.config', 'sample_data']

In [11]:
df.to_csv("textwin_sensor_dataset.csv", index=False)

import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'textwin_sensor_dataset.csv', 'sample_data']

In [12]:
from google.colab import files

files.download("/content/textwin_sensor_dataset.csv")